version: '3.1'

services:
    db_container:
        image: mysql:8.0
        environment:
          MYSQL_DATABASE: Pictures
          MYSQL_USER: mbit
          MYSQL_PASSWORD: mbit
          MYSQL_ROOT_PASSWORD: mbit
        command: --default-authentication-plugin=mysql_native_password
        ports:
          - 3306:3306
        expose:
          - '3306'
        volumes:
          - mysql_db_data:/var/lib/mysql
          - ./db_schemas:/docker-entrypoint-initdb.d
    adminer_container:
      image: adminer:4.5.0
      environment:
        ADMINER_DEFAULT_SERVER: db_container
      ports:
        - 8080:8080


volumes:
  mysql_db_data: