version: '3.1'

services:
  db_container:
      image: mysql:8.0
      environment:
        MYSQL_DATABASE: Pictures
        MYSQL_USER: mbit
        MYSQL_PASSWORD: mbit
      command: --default-authentication-plugin=mysql_native_password
      ports:
        - 3306:3306
      expose:
        - '3306'
      volumes:
        - mysql_db_data:/var/lib/mysql
        - ./db_schemas:/docker-entrypoint-initdb.d
  adminer_container:
    image: adminer:4.5.0
    environment:
      ADMINER_DEFAULT_SERVER: db_container
    ports:
      - 8080:8080
  web_container:
    image: app
    build: ./app   # Path to the directory containing the Dockerfile
    ports:
      - "5005:5005"
    environment:
      - CREDENTIAL_PATH=/app/app/credentials.json
      - HOST_APP=db_container
      - DATABASE_APP=Pictures
      - USER_APP=mbit
      - PASSWORD_APP=mbit
      - RESULT_PATH=/static/results
    volumes:
      - ./static:/static
    depends_on:
      - db_container

volumes:
  mysql_db_data: